### ISSUE TITLE
Two-Way Syncing Issue & PDF Uploading Issue

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#59] opened 2016-03-17 16:53 UTC
Database: lawfirm.com
Client: Acme
Matter: 008

When I linked 008t to the family, the references did not flow.
I could not upload PDFs to NPL67 and NPL68

**Comment by ntgn81** [comment] 2016-03-17 17:40
@JulieJager , which browser are you on? I was able to create 008t and link it into 008 family.

**Comment by ntgn81** [comment] 2016-03-17 17:56
@JulieJager , I fixed file upload. I'm not able to reproduce the linking though. Can you?

**Comment by JulieJager** [comment] 2016-03-17 18:08
Nevermind. Yesterday, I deleted all the uncited references is 008, and removed 008 from the family to prepare for another demo today.  So, when I added 008 to the family today, SyncIDS did the right thing in that it didn't return the DeletedArt when I resynced.  Pretty sure we're ok.  So sorry.

**Comment by ntgn81** [comment] 2016-03-17 19:30
Awesome, closing this issue.

**Closed by ntgn81** 2016-03-17 19:30 UTC
