### ISSUE TITLE
Bug Report: unable to mark matters as filed

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#521] opened 2016-09-01 02:25 UTC
Parklegal:  I’m having an issue with receiving that Failed to File Matter error again.  The docket no. for the IDS’ I filed are SCTY-P272-1NUS and SCTY-P273-1NUS.  Please let me know if you need anything else from me.

**Comment by JulieJager** [comment] 2016-09-01 03:37
I see that both of these were "Filed" properly according to the SQL.  They must be seeing a Failed Status Tag?

**Comment by JulieJager** [comment] 2016-09-21 02:48
@yneves Was this resolved?

**Comment by yneves** [comment] 2016-09-21 21:08
Yes, just tested the same scenario. I'll add an automated test for this case.

**Comment by yneves** [comment] 2016-09-21 22:35
Actually, i'm not so sure anymore, i'll double check.

**Comment by yneves** [comment] 2016-09-21 22:44
@JulieJager @ntgn81 It's really not fixed yet. I'm getting `Error: Matter does not have documents ready to be cited.` on API. There weren't any documents marked as cited, so i'm not sure if we should change the API or just let the user know why its failing.

**Comment by ntgn81** [comment] 2016-09-21 22:45
Is that still an issue though? This is related to first time user trying to file a matter with somethign to file, right?

**Comment by yneves** [comment] 2016-09-21 22:48
@ntgn81 It's still happening. To reproduce:

1) create a new client
2) create a new matter
3) fill required information
4) create one doc of each kind without all info
5) try to file, you'll get this error

**Comment by yneves** [comment] 2016-09-21 22:49
Or use the test script i created here #564 :-)

**Comment by ntgn81** [comment] 2016-09-22 00:17
That's fine. Docs without information are not file-able. Unless you enter us doc that gets resolved properly. Which doc did you enter for US?

**Comment by yneves** [comment] 2016-09-27 22:39
Since there's nothing we can do, i changed API and UI to show the reason why the matter can't be filed.  It shows a yellow notification with server message.

**Closed by yneves** 2016-09-27 22:39 UTC
